//AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const GET_USER = "GET_USER";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";

//JOBS
export const JOB_SCRAPING_START = "JOB_SCRAPING_START";
export const JOB_SCRAPING_SUCCESS = "JOB_SCRAPING_SUCCESS";
export const JOB_SCRAPING_FAIL = "JOB_SCRAPING_FAIL";

export const GET_JOB_START = "GET_JOB_START";
export const GET_JOB_SUCCESS = "GET_JOB_SUCCESS";
export const GET_JOB_FAIL = "GET_JOB_FAIL";

export const DELETE_JOB_START = "DELETE_JOB_START";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";

export const GET_CK_START = "GET_CK_START";
export const GET_CK_SUCCESS = "GET_CK_SUCCESS";
export const GET_CK_FAIL = "GET_CK_FAIL";

//APPLICANTS
export const APPLICANT_SCRAPING_START = "APPLICANT_SCRAPING_START";
export const APPLICANT_SCRAPING_SUCCESS = "APPLICANT_SCRAPING_SUCCESS";
export const APPLICANT_SCRAPING_FAIL = "APPLICANT_SCRAPING_FAIL";

export const GET_APPLICANT_START = "GET_APPLICANT_START";
export const GET_APPLICANT_SUCCESS = "GET_APPLICANT_SUCCESS";
export const GET_APPLICANT_FAIL = "GET_APPLICANT_FAIL";

export const DELETE_APPLICANT_START = "DELETE_APPLICANT_START";
export const DELETE_APPLICANT_SUCCESS = "DELETE_APPLICANT_SUCCESS";
export const DELETE_APPLICANT_FAIL = "DELETE_APPLICANT_FAIL";

export const GETSCORE_APPLICANT_START = "GETSCORE_APPLICANT_START";
export const GETSCORE_APPLICANT_SUCCESS = "GETSCORE_APPLICANT_SUCCESS";
export const GETSCORE_APPLICANT_FAIL = "GETSCORE_APPLICANT_FAIL";

//MODAL
export const MODAL_RESET = "MODAL_RESET";
